# This Workflow Builds, Tests, Lints, and Deploys the UI and API to Heroku
name: CICD for Main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  build-and-test-app:
    name: Build and Test UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build UI
        run: |
          docker build -t ussf-hha-app ./app
      - name: Test UI
        run: |
          docker run -e CI=true ussf-hha-app npm test
  owasp-zap-scan:
    name: Build and Scan w/OWASP-Zap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build UI
        run: |
          docker build -t ussf-hha-app ./app
      - name: Run Server
        run: |
          docker run -e CI=true ussf-hha-app nohup npm run start &
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://0.0.0.0:3000'
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        
        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
        # queries: security-extended,security-and-quality

        
    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

    #   If the Autobuild fails above, remove it and uncomment the following three lines. 
    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

    # - run: |
    #   echo "Run, Build Application using script"
    #   ./location_of_script_within_repo/buildscript.sh

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
  deploy-ui:
    name: Deploy UI to Heroku
    # Needs specifies the steps that must previously complete in order to deploy your application.
    needs: [ build-and-test-app, analyze ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ussf-hha"
          heroku_email: "alexhartenburg@gmail.com"
          appdir: "app/"
          usedocker: true
