name: Testing on Pushes to All Branches

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - '**'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# 'jobs' is the list of all the workflows that will kick off.
jobs:
  # This workflow kicks off the build and test for the UI
  build-and-test-ui:
    # Name of the build job
    name: Build and Test UI
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # `steps` are the actions that will execute on this job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell to build the UI
      - name: Build UI
        run: |
          docker build -t ussf-hha-app ./app
      # Runs a set of commands using the runners shell to test the UI
 #     - name: Test UI
 #       run: |
 #         docker run -e CI=true bsdi-crud-app npm test
