name: Testing on Pushes to All Branches

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - '**'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
