name: Build and Test on all Pushes & PRs

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:
  
jobs:
  build-and-test-ui:
    name: Build and Test UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build UI
        run: |
          docker build -t ussf-hha-app ./app
      - name: Test UI
        run: |
          docker run -e CI=true ussf-hha-app npm test